source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Feeder_Example', :exclusive => true do
  pod "Feeder", :path => "../"
end

target 'Feeder_Tests', :exclusive => true do
  pod "Feeder", :path => "../"

  
end
